name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    permissions:  read-all


    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy Static Website
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ c5c9812a132ea673389d9d3742468c998dc691d8ef1759e682dfe262dc68025806-e7c55b21-52bd-45d4-a67c-8e27ac53ebf400f162504357160f }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request

    steps:
      - name: Close Preview Deployment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ 24fb7a4f44bf3447443c295c09b415976bb81edf5c3990fa2b994a05cc75a18d06-3c7fc3aa-7f2c-4630-b881-d806f19f275e00f162504357160f }}
          action: "close"
